name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: sark1/GithubActions-Workflow/.github/workflows/buildAndPublishDockerImage.yml@main
    with:
      image_name: azureawsgcsdk
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
  java:
    uses: sark1/GithubActions-Workflow/.github/workflows/buildAndPublishDockerImage.yml@main
    with:
      image_name: azureawsgcsdk
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
