name: test1
on: 
  workflow_call: 
    inputs:
      url1:
        required: true
        type: string 

jobs:
  get_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'powershell'
        shell: pwsh
        run: |
              Install-Module powershell-yaml -force
              Import-Module powershell-yaml -Force
              invoke-webrequest -Uri ${{inputs.url1}} -OutFile "abcd.html"
              Write-Host "Artifact Verified !!!"
      - name: 'finding path'
        run: readlink -f abcd
      - name: 'upload'
        uses: actions/upload-artifact@v2
        with: 
          name: 'abcd.html'
          path: /home/runner/work/GithubActions-Workflow/GithubActions-Workflow/abcd.html
        
