name: test1
on:
  push:
jobs:
  get_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: 'powershell'
        shell: pwsh
        run: |
             'invoke-webrequest -Uri "https://github.com/sark1/GithubActions-Workflow/blob/main/Dockerfile" -OutFile "abcd.txt"'
             'Write-Host "Artifact Verified !!!"'
