name: test1
on: 
  workflow_call: 
    inputs:
      url1:
        required: true
        type: string 

jobs:
  get_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'powershell'
        shell: pwsh
        run: |
              Install-Module powershell-yaml -force
              Import-Module powershell-yaml -Force
              invoke-webrequest -Uri ${{inputs.url1}} -OutFile "abcd.txt"
              Write-Host "Artifact Verified !!!"
        
